// <auto-generated />
using CVBuilder.Contracts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CVBuilder.Migrations.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260206204118_AddCvTemplatesTable")]
    partial class AddCvTemplatesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CVBuilder.Contracts.EfItem<CVBuilder.Contracts.CvTemplate>", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<CvTemplate>("Content")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("CvTemplates", (string)null);
                });

            modelBuilder.Entity("CVBuilder.Contracts.EfItem<CVBuilder.Contracts.User>", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<User>("Content")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("Users", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("CVBuilder.Contracts.EfItem<CVBuilder.Contracts.UserIdentity>", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<UserIdentity>("Content")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Content");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Content"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Content"), new[] { "jsonb_path_ops" });

                    b.ToTable("UserIdentities");
                });
#pragma warning restore 612, 618
        }
    }
}
